### PR TITLE
Include unbundled build in gulpfile

### LINKED ISSUE #55: [feature request] Add flag to enable/disable bundler
It would be nice to have a flag that disables the bundler because bundling might not be needed (e.g., using `h2`) or wanted (e.g., https://github.com/Polymer/polymer-build/issues/110).

### PR DESCRIPTION
**Pull request by andrewweaver**
Feel free to reject this merge if it is not the overall goal of the project, but I thought it would be nice to include a bundled and unbundled version of this project. 

The changes include piping the project to an unbundled directory before sending to the bundler. Also added to the promise chain to include the generation of both service workers.

This would resolve #55

### CODE REVIEW

**Comment by robdodson** [comment]
@andrewweaver have you found yourself needing both a bundled and an unbundled version of the same project? I was thinking folks might prefer a top level boolean that they can set to produce one or the other.

**Comment by andrewweaver** [comment]
@robdodson I agree with your idea of using a simple boolean to generate one project or the other. We tend to generate both a bundled and unbundled version as some of our test/staging servers do support H2 but not all of them. This is probably a limited case as to where people would need a similar solution, that being said it at least gives choice.

**Comment by robdodson** [comment]
We used to generate both bundled and unbundled output in a previous version of this generator but I think folks preferred one or the other. @FredKSchott wdyt

**Comment by andrewweaver** [comment]
@robdodson Thats really the reason I submitted the PR, simply because we do use both (because it was in the old version.)  I wasn't sure of how many other people used it, and thought others may like the old solution.

**Comment by jsilvermist** [comment]
What about 2 top level booleans used to toggle both bundled and unbundled for people who want either 1 or both?

**Comment by FredKSchott** [comment]
@robdodson correct me if I'm wrong, but our goal when writing the current gulpfile was to be as simple as possible to 1) understand and 2) modify/customize. With that in mind, I don't think that this change makes sense to merge into custom-build. But I love(!) to see how easy it was for you to make this change in your own gulpfile, since modifying and extending what is written was exactly what we wanted to encourage and make as easy as possible.

Also slightly related: we're changing the Polymer CLI to generate a single build by default. So while `bundled` & `unbundled` may feel a a little more "default" now, I think it will be less requested once that CLI change is released.

**Comment by andrewweaver** [comment]
@FredKSchott Thanks for the heads up! Feel free to close!

Side Note: Absolutely love the idea of Promise chaining gulpfiles!

**Pull request closed without merging**
