### PR TITLE
[WIP] Get config by parameter in the project task

### PR DESCRIPTION
**Pull request by abdonrd**
WIP. Do not merge.

Fix https://github.com/PolymerElements/generator-polymer-init-custom-build/issues/40

### CODE REVIEW

**Comment by robdodson** [comment]
@abdonrd would you mind changing the name back to project.js, it makes it difficult to track what the actual changes are

**Comment by abdonrd** [comment]
@robdodson done!

**Comment by robdodson** [comment]
Thanks @abdonrd. I see where you're going with this and I like the idea of passing the config object in as a parameter. Rather than version up this one task I think it might be good to spend some time on a separate project where we actually consolidate all of the gulp tasks and make them more consistent. I like the way that the wsk-tasks (https://github.com/google/web-starter-kit/blob/wsk2/src/wsk-tasks/html.js) only expose two functions, `build` and `watch`. I wonder if we could do something similar...

I'll create a repo for the gulp tasks and invite you and @chuckh to it so we can work on ideas over there

**Comment by abdonrd** [comment]
@robdodson why `watch` function? I think we need all the functions from the `PolymerProject` class.

**Comment by stramel** [comment]
Totally in favor of a watch task even if it isn't part of this PR. :+1:

**Comment by abdonrd** [comment]
Friendly ping to @robdodson and @chuckh :)

**Comment by robdodson** [comment]
Sorry it took me so long to get around to this.

After talking with @fredkschott yesterday, I think we may move away from the gulpfile approach we've used in custom-build. Fred tells me that a lot of folks who are new to polymer-build are having a hard time understanding the gulpfile. I think we could probably simplify it by providing a [promisified](https://gist.github.com/robdodson/b31fb1c9da773eb6d7b63e44b60ec08f) or [async function](https://gist.github.com/robdodson/73be1e9a7cc94a199ff6cbdca2208760) gulpfile. Async functions are available in Node 7 using the `--harmony-async-await` flag, so when that ships maybe we could migrate to that since it's cleaner than promises.

**Comment by FredKSchott** [comment]
Just to add to what @robdodson said, custom-build is our most common introduction to polymer-build, how it works, how to use it, and how to customize it. The current gulpfile is powerful, but very hard to understand and debug by looking at it. I've had to jump into several users projects now to help them find build bugs, because they couldn't follow the gulpfile as it exists today.

I think we'd better serve our users with something like either of the gists that @robdodson shared above. By making the process linear, we make it much easier to follow and understand. And by using in-code documentation vs. a big god config object, it's much easier to see how those configuration options actually work in polymer-build.

**Comment by abdonrd** [comment]
Ok! SGTM. @robdodson, do you make a PR?

**Comment by robdodson** [comment]
yep, I was maybe going to wait till polymer-build v0.6.0 comes out which
should be soon

**Comment by abdonrd** [comment]
polymer-build v0.6.0 is out!
https://github.com/Polymer/polymer-build/releases/tag/v0.6.0

Ping to @robdodson :)

**Comment by robdodson** [comment]
I don't think I can get to this today so if you want to take a crack at
porting the gulpfile over that would be great, otherwise I'll follow up
tomorrow afternoon

**Comment by abdonrd** [comment]
@robdodson Ok!

But the actual PSK already has a `package.json`. How are we going to manage this?
And, the Polycast script hasn't the Service Worker created.

**Comment by abdonrd** [comment]
New PR: https://github.com/PolymerElements/generator-polymer-init-custom-build/pull/51

**Pull request closed without merging**
